### ISSUE TITLE
problem in reusing Mixin robot's ID

### ISSUE THREAD

**Issue by yijunyu** [MixinNetwork/supergroup.mixin.one#203]
Not sure if any one has encountered this problem before.

I intend to reuse another Mixin app "A" to reconfigure it as a supergroup app "B", instead of creating a new Mixin app. 

In the Mixin Developer Dashboard, both "Home URL" and "OAuth URL" have been reconfigured to the new server location, along with the session information in the "config.yaml". 

"Home URL": https://B's URL
"OAuth URL": https://B's URL/auth

However, every time the OAuth URL will redirect me to A's URL, and the QR code is also showing the A's icon. 

https://mixin.one/oauth/authorize?client_id=<A's client id>&scope=PROFILE:READ+ASSETS:READ+MESSAGES:REPRESENT&response_type=code&return_to=%2F

Is this problem caused by Mixin Networks or the App ? 
I also don't know how to delete an existing Mixin app from the Dashboard so don't know how to create this App without creating the ID from scratch.

**Comment by jadeydi** [comment]
```
https://mixin.one/oauth/authorize?client_id=<A's client id>&scope=PROFILE:READ+ASSETS:READ+MESSAGES:REPRESENT&response_type=code&return_to=%2F
```
You should use B's client id, not A's

**Comment by yijunyu** [comment]
I knew, however, this URL was generated by the supergroup app. It redirects me to this URL using the older client A's ID rather than B's ID, even though my config.yaml already declares the client_id using B's ID.

**Comment by jadeydi** [comment]
You need to change both back-end and front-end client A's ID. `config.yaml` is for back-end, `web.env.production.local` for front-end

**Comment by yijunyu** [comment]
The problem is solved using your suggestion, thank you!
