### ISSUE TITLE
红包详情查看不了

### ISSUE THREAD

**Issue by solarzhong** [MixinNetwork/supergroup.mixin.one#6]
Hi，fork了一份代码建了个测试群，聊天功能等都可用，红包也能发。但是双击红包显示出来的详情页不对，感觉应该是config.go里 HTTPResourceHost这个参数的问题啊。

**Comment by jadeydi** [comment]
对比了参数，跟中文群用得是一样的。详情页不对是什么意思？
HTTPResourceHost 的值，应该是红包地址的域名部分。

**Comment by solarzhong** [comment]
谢回，就是双击红包打开后，标题是正在加载....，其他是空白的。
我用的参数是这个。https://chinese-group.mixin.test。我看这个域名也访问不了呀

**Comment by jadeydi** [comment]
你要换成自己的域名才行，你红包网页的域名

**Comment by solarzhong** [comment]
可以了，谢谢。
